baseURL		  = "http://yulunz.me/"
languageCode 	  = "en-US"

description 	  = "Personal website of Yulun Zeng"

disqusShortname   = "yulunzeng"
enableEmoji 	  = true
builddrafts	  = false
author		  = "Yulun Zeng"
title		  = "Yulun Zeng"
faviconfile	  = ""

[[menu.main]]
name		  = "About"
weight		  = -120
identifier	  = "about"
url		  = "/about/"

[[menu.main]]
name		  = "Blog"
weight		  = -120
identifier	  = "blog"
url		  = "/blog/"

[params]
i18n_flags	  = true
linkedin	  = "//linkedin.com/in/yulunzeng"
twitter		  = "//twitter.com/ligerleng"
author		  = "花间一壶酒"
avatar		  = "img/profile-4.jpg"
noshowreadtime	  = true