baseURL		  = "/"
languageCode 	  = "en-US"
description 	  = "Personal website of Yulun Zeng"
enableEmoji 	  = true
builddrafts	  = false
author		  = "Yulun Zeng"
title		  = "Yulun Zeng"
faviconfile	  = ""
disqusShortname   = "yulunzeng"
googleAnalytics	  = "UA-108088773-1"

[[menu.main]]
name		  = "About"
weight		  = -120
identifier	  = "about"
url		  = "about"

[[menu.main]]
name		  = "Blog"
weight		  = -120
identifier	  = "blog"
url		  = "blog/"

[params]
linkedin	  = "//linkedin.com/in/yulunzeng"
twitter		  = "//twitter.com/thekinval"
github		  = "//github.com/yulunz"
author		  = "The Responsible Adult"
avatar		  = "img/profile-4.jpg"
noshowreadtime	  = true
faviconfile	  = "img/dummyPicTrans.png"